### ISSUE TITLE
希望可以增加以下公众号的RSS源

### ISSUE THREAD

**Issue by Victormanchiu** [osnsyc/Wechat-Scholar#3]
您好，我是通过少数派读到您的文章，也萌发了利用RSS集中管理科研公众号的想法（公众号充斥着科研和娱乐，确实很割裂）。我是从事纳米药物方向的在读博士生，平常关注的公众号偏向生物材料和纳米医学，希望可以增加以下公众号RSS源，万分感谢！公众号：药学学报、纳米药物前沿、NanoBioMaterials、NanoResearch、药学进展、铁死亡研究、奇点肿瘤探秘、纳米酶论、铁死亡Club。

**Comment by osnsyc** [comment]
已更新（除`铁死亡Club`），请于[channels.json](https://github.com/osnsyc/Wechat-Scholar/blob/main/channels.json)内查询订阅，`铁死亡Club`将在下次公众号更新时收录，请留意后续commits

**Comment by Victormanchiu** [comment]
thx~
