### ISSUE TITLE
感谢博主的无私分享，希望增加以下公众号

### ISSUE THREAD

**Issue by hdqzzz** [osnsyc/Wechat-Scholar#4]
博主您好，从少数派了解到您高效追踪学术动态的工作流，个人受益匪浅。我本人主要关注并从事大模型(NLP/CV)和AIGC相关方向的技术工作，也曾尝试通过werss订阅公众号，可惜目前已不再开放新订阅。不知道是否方便在您的RSS Channel中也增加下列学术资讯类的订阅？具体包括：
> AIGC开放社区
AINLPer
极市平台
计算机视觉联盟
深度学习自然语言处理
Mindverse Research
NLP工作站
AI科技评论
夕小瑶科技说
扬奇智能社区
天街知事
AI for Research
爱可可爱生活
机器学习算法与自然语言处理
深度学习与NLP
我爱计算机视觉
arXiv每日学术速递
专知
AINLP
人工智能前沿讲习
PaperWeekly
赛尔实验室
微软亚洲研究院
机器学习研究组订阅

**Comment by osnsyc** [comment]
- `天街知事`不符合收录要求；
- 其它频道将在下次公众号更新文章时收录，请留意后续commits，于[channels.json](https://github.com/osnsyc/Wechat-Scholar/blob/main/channels.json)内查询订阅

**Comment by hdqzzz** [comment]
感谢博主支持，天街知事是我疏漏不应该包含进来，期待更新👏
