### ISSUE TITLE
能否麻烦楼主增加一些订阅，辛苦！

### ISSUE THREAD

**Issue by ZhenhongDu** [osnsyc/Wechat-Scholar#5]
楼主您好，我对脑科学和光学以及计算机的一些公众号感兴趣，能麻烦您增加一些公众号订阅吗？
谢谢楼主啦~

> 中国光学
> AIWalker
> 小柯生命
> 煤矿工厂
> brainnews
> IntelligentOptics
> Photonix
> 中国激光杂志社

**Comment by osnsyc** [comment]
将在下次公众号更新文章时收录，请留意后续commits，于[channels.json](https://github.com/osnsyc/Wechat-Scholar/blob/main/channels.json)内查询订阅
