### ISSUE TITLE
有几天没更新了，来看看博主

### ISSUE THREAD

**Issue by hdqzzz** [osnsyc/Wechat-Scholar#6]
有几天没更新了，来看看博主

**Comment by mimicosnsyc** [comment]
github账号被盗，在申诉中，账号已冻结。账号找回后会继续更新。

> We have not forgotten about you. We’ve been experiencing a high volume of tickets, driven by a greater than expected growth in customers. We have concrete plans to return to the responsive standard we are known for. Trust that your ticket is still in our queue and we’ll get you an answer as quickly as we can.

吐槽一下github的处理效率

**Comment by hdqzzz** [comment]
是不是github还没处理好，要不要考虑新开个repo。。

**Comment by osnsyc** [comment]
已恢复
