### ISSUE TITLE
非常不错的项目，加公众号

### ISSUE THREAD

**Issue by xhhjin** [osnsyc/Wechat-Scholar#8]
非常不错的项目！
希望方便的话能增加两个公众号，感谢啦~

> AIGC Studio
AIGC Research

**Comment by osnsyc** [comment]
https://raw.githubusercontent.com/osnsyc/Wechat-Scholar/main/channels/gh_4e78d3dc1e48.xml
https://raw.githubusercontent.com/osnsyc/Wechat-Scholar/main/channels/gh_5ba19d995457.xml
