### ISSUE TITLE
希望加一些公众号 谢谢

### ISSUE THREAD

**Issue by TianyuHe42** [osnsyc/Wechat-Scholar#9]
追问nextquestion
Nature Portfolio
脑机接口社区
集智俱乐部
饶议科学

**Comment by osnsyc** [comment]
https://raw.githubusercontent.com/osnsyc/Wechat-Scholar/main/channels/gh_481ee48e3261.xml
https://raw.githubusercontent.com/osnsyc/Wechat-Scholar/main/channels/gh_900a436f047a.xml
https://raw.githubusercontent.com/osnsyc/Wechat-Scholar/main/channels/gh_9067bcbdd631.xml
https://raw.githubusercontent.com/osnsyc/Wechat-Scholar/main/channels/gh_93725664f16e.xml
https://raw.githubusercontent.com/osnsyc/Wechat-Scholar/main/channels/gh_2414d982daee.xml
